[target.xtensa-esp32-none-elf]
runner = "./flash.sh"

[env]
ESP_LOG="info"
ESP_HAL_CONFIG_PLACE_RMT_DRIVER_IN_RAM="true"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-Z", "stack-protector=all",
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"]
#build-std-features = ["panic_immediate_abort"]